global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "linux-nodes"
    file_sd_configs:
      - files:
          - /etc/prometheus/linux-targets.yml

  - job_name: "linux-processes"
    file_sd_configs:
      - files:
          - /etc/prometheus/linux-process-targets.yml

  - job_name: "windows-nodes"
    file_sd_configs:
      - files:
          - /etc/prometheus/windows-targets.yml
